from __future__ import annotations

import json
from pathlib import Path

DEFAULT_SYNTHETIC_REPORT_PATH = (
    Path(__file__).resolve().parent.parent / "frontend" / "data" / "report.json"
)

PROVENANCE = "synthetic_crash_test"


def load_synthetic_report(path: str | Path = DEFAULT_SYNTHETIC_REPORT_PATH) -> dict:
    path = Path(path)
    if not path.exists():
        raise FileNotFoundError(
            f"Synthetic Polygraph report not found at {path}. "
            f"Run `python3 backend/main.py` to generate it - this loader does not generate it itself."
        )
    with open(path, "r") as f:
        data = json.load(f)

    return {
        "provenance": PROVENANCE,
        "source_note": (
            "Generated by Agent Polygraph's synthetic scenario engine (backend/). "
            "Not historical, not a backtest, not real trading data."
        ),
        "report": data,
    }
